# Generated by Django 3.0.6 on 2020-06-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='short',
            new_name='slug',
        ),
    ]
